"""Initial migration

Revision ID: 60db1c2d621d
Revises:
Create Date: 2026-06-18 01:48:05.993031

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "60db1c2d621d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
